name: Build All PHP Versions

on:
  workflow_dispatch:
  schedule:
    # Run on the 1st day of every month at 1:00 AM UTC (before individual builds)
    - cron: '0 1 1 * *'

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  # Build all PHP versions using workflow_call (runs builds in parallel)
  build-php-56:
    uses: ./.github/workflows/php-56.yml
    secrets: inherit
    
  build-php-72:
    uses: ./.github/workflows/php-72.yml
    secrets: inherit
    
  build-php-74:
    uses: ./.github/workflows/php-74.yml
    secrets: inherit
    
  build-php-81:
    uses: ./.github/workflows/php-81.yml
    secrets: inherit
    
  build-php-82:
    uses: ./.github/workflows/php-82.yml
    secrets: inherit
    
  build-php-83:
    uses: ./.github/workflows/php-83.yml
    secrets: inherit